### ISSUE TITLE
[Bug] Can't Safety Roll After Jumping Off A Swing Rope

### ISSUE THREAD

**Issue by CootieDwagon** [JonnyBro/beatrun#124]
Describe the bug:
when jumping off a swing rope, you can NOT roll by pressing left ctrl key. you can however roll by pressing left shift.

1. load up any map
2. spawn in a swing rope
3. swing from the rope, jump and try to roll with left ctrl key
4. you won't be able to roll with left ctrl key

Expected behavior:
I thought a swing rope would be similar to a grapple hook in some ways. with the grapple hook, if you jump off from it you can roll
by pressing left ctrl key and left shift.

**Additional information:**
 - Game Version: non-beta
- Game Type: singleplayer

Additional context:
so with the grapple hook, you can roll if you press left ctrl key, but this does not work for swing ropes. which is weird cause the only difference really between them is, one can be used in free mode and the other is used for courses to "swing" on.

**Comment by c4nkerm3me** [comment]
Basically the issue here is that when you use a grappling hook, the crouch jump isn't disabled.
But when using a swing rope, its usually disabled.
Safety Roll works with three different keybinds, defined by "IN_DUCK", "IN_SPEED" or "IN_BULLRUSH", not just one.
But because of crouch jump being disabled, Safety Roll only uses "IN_SPEED" and "IN_BULLRUSH". The opposite happens when its not disabled, it uses "IN_DUCK".

Here are the screenshots for reference and (what i assume) finding these issues.
![image](https://github.com/JonnyBro/beatrun/assets/89845830/57d66866-89b2-4656-80b9-59c77751ee78)
![image](https://github.com/JonnyBro/beatrun/assets/89845830/893191a1-0f49-4ab3-98b0-1559304f9717)
![image](https://github.com/JonnyBro/beatrun/assets/89845830/75c43560-974e-4c33-9514-d4829ef7e42c)

**Comment by c4nkerm3me** [comment]
The only issue I found with doing this, is that your character does weird stuff when trying to crouch jump.
To prevent that, I'd disable crouch jumping when i jump off a grapple or swing rope. Not always leave it enabled.

**Comment by CootieDwagon** [comment]
> The only issue I found with doing this, is that your character does weird stuff when trying to crouch jump. To prevent that, I'd enable crouch jumping ONLY when I jump off a grapple or swing rope. Not ALWAYS leave it enabled.

you have found this information which is interesting... are you aware the same thing happens when you come off a zipline?

yeah, when you get off of a zipline, the left control key doesn't work to "safety roll" but the "left shift" key still works

**Comment by JonnyBro** [comment]
Fixed in https://github.com/JonnyBro/beatrun/commit/78f949eb66e4552be50b950975c415ff9ec55d72
