### ISSUE TITLE
[Bug] Skinny/Broken fingers

### ISSUE THREAD

**Issue by wrightistheidiot** [JonnyBro/beatrun#177]
**Describe the bug**
Fingers on playermodels appear "broken" or extremely skinny

**To Reproduce**
1. Have custom playermodels
2. Probably done

**Expected behavior**
I know it's an issue with some other addons, but it's the most apparent in beatrun for me.

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional information:**
 - x64
- Game Type: singleplayer
![image](https://github.com/JonnyBro/beatrun/assets/165412748/73df4680-1c51-4231-9a8c-a54bd8d1888c)
![image](https://github.com/JonnyBro/beatrun/assets/165412748/27ea223c-c1b5-4046-9a4b-53de9d701de9)
![image](https://github.com/JonnyBro/beatrun/assets/165412748/81d61b4b-65f9-4396-88d8-33fa0ce8b2e1)
![image](https://github.com/JonnyBro/beatrun/assets/165412748/6d5addee-9d32-4eb7-8f97-f9869903e99d)

**Comment by LeJuanKM** [comment]
Since Jonny doesn't want to elaborate, I hope I can help. This is probably just a badly weight painted playermodel or bones being lazily placed. It has nothing to do with beatrun I'd say. Some playermodels get really fucked up with the beatrun's animations and other's fit perfectly. The more accurate the weight paint and bone placements the better the animations will look.

**Comment by JonnyBro** [comment]
> Since Jonny doesn't want to elaborate, I hope I can help. This is probably just a badly weight painted playermodel or bones being lazily placed. It has nothing to do with beatrun I'd say. Some playermodels get really fucked up with the beatrun's animations and other's fit perfectly. The more accurate the weight paint and bone placements the better the animations will look.

I see now, thank you. I don't know much about Source modeling so I don't have that much knowledge about that.
