### ISSUE TITLE
[Bug] Dive is a default slide

### ISSUE THREAD

**Issue by Didtruo** [JonnyBro/beatrun#88]
If you play singleplayer, by diving you are changing immediately animation to slide with foot after landing on ground
problem doesnt occure in multiplayer.
**To Reproduce**
1. Open game in singleplayer
2. Dive

**Expected behavior**
It should continue sliding animation on stomach other than default slide

**Screenshots/Videos**
Issue.mp4 shows what i mean
Multiplayer.mp4 shows what should happen

**Additional information:**
 - Game Version: chromium, x64
- Game Type: singleplayer

**Additional context**
Havent changed any beatrun settings, bug happens even without any addons *only map, playermodel and gamemode, happens on every map*.

Video representing the issue:

https://github.com/JonnyBro/beatrun/assets/146891537/0ca67bbf-cdbd-4191-8323-00e093dcef25

What should happen i show in Multiplayer.mp4:

https://github.com/JonnyBro/beatrun/assets/146891537/727e8022-f1c7-44de-b45e-b03626d41720

**Comment by JonnyBro** [comment]
it's a known bug

**Comment by CootieDwagon** [comment]
this same bug thing happens when you flop onto your back in single player. i recently went back and played the first mirrors edge game, and when you flop onto your back after running forward, it is supposed to stop ALL momentum and keep you flopped onto your back. but for some reason this addon doesn't do that, it forces you into a slide when you flop onto your back after moving forward.

**Comment by JonnyBro** [comment]
is it fixed now?

**Comment by Didtruo** [comment]
yes

**Comment by Didtruo** [comment]
it seems the issue came back and its now broken again

**Comment by Didtruo** [comment]
it started working for some reason but it works now
